update yml file

diff --git a/.github/workflows/workflow.yml b/.github/workflows/workflow.yml
--- a/.github/workflows/workflow.yml
+++ b/.github/workflows/workflow.yml
@@ -9,20 +9,23 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
-      - uses: cpp-linter/cpp-linter-action@v2
-        id: linter
-        continue-on-error: true
-        env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
-        with:
-          style: file
-          files-changed-only: false
+  #     - uses: cpp-linter/cpp-linter-action@v2
+  #       id: linter
+  #       continue-on-error: true
+  #       env:
+  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+  #       with:
+  #         style: file
+  #         files-changed-only: false
 
-      - name: Fail fast?!
-        if: steps.linter.outputs.checks-failed != 0
-        run: |
-          echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
-          exit 1
+  #     - name: Fail fast?!
+  #       if: steps.linter.outputs.checks-failed != 0
+  #       run: |
+  #         echo "some linter checks failed. ${{ steps.linter.outputs.checks-failed }}"
+  #         exit 1
+      
+      - name: Linter
+        run: make linter
       
       - name: Tester
         run: make re test; make re debug=true test
